// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace NativeMLAOT
{
    /// <summary>
    /// model input class for MLModel1.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"age")]
        public float Age { get; set; }

        [ColumnName(@"workclass")]
        public string Workclass { get; set; }

        [ColumnName(@"fnlwgt")]
        public float Fnlwgt { get; set; }

        [ColumnName(@"education")]
        public string Education { get; set; }

        [ColumnName(@"education-num")]
        public float Education_num { get; set; }

        [ColumnName(@"marital-status")]
        public string Marital_status { get; set; }

        [ColumnName(@"occupation")]
        public string Occupation { get; set; }

        [ColumnName(@"relationship")]
        public string Relationship { get; set; }

        [ColumnName(@"ethnicity")]
        public string Ethnicity { get; set; }

        [ColumnName(@"sex")]
        public string Sex { get; set; }

        [ColumnName(@"capital-gain")]
        public float Capital_gain { get; set; }

        [ColumnName(@"capital-loss")]
        public float Capital_loss { get; set; }

        [ColumnName(@"hours-per-week")]
        public float Hours_per_week { get; set; }

        [ColumnName(@"native-country")]
        public string Native_country { get; set; }

        [ColumnName(@"label(IsOver50K)")]
        public bool Label_IsOver50K_ { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel1.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public bool Prediction { get; set; }

        public float Score { get; set; }

        // The probability calculated by calibrating the score of having true as the label.
        public float Probability { get; set; }
    }

    #endregion

}
